// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/container/index.vue')['default']
    Dialog: typeof import('./src/components/iTeachTest/tbform/dialog.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ITeachTest: typeof import('./src/components/iTeachTest/index.vue')['default']
    Menu: typeof import('./src/components/iTeachTest/menu/index.vue')['default']
    NavHeader: typeof import('./src/components/container/components/nav-header.vue')['default']
    SideMenu: typeof import('./src/components/container/components/side-menu.vue')['default']
    VabQueryForm: typeof import('./src/components/iTeachTest/VabQueryForm/index.vue')['default']
    VabQueryFormBottomPanel: typeof import('./src/components/iTeachTest/VabQueryForm/components/VabQueryFormBottomPanel.vue')['default']
    VabQueryFormLeftPanel: typeof import('./src/components/iTeachTest/VabQueryForm/components/VabQueryFormLeftPanel.vue')['default']
    VabQueryFormRightPanel: typeof import('./src/components/iTeachTest/VabQueryForm/components/VabQueryFormRightPanel.vue')['default']
    VabQueryFormTopPanel: typeof import('./src/components/iTeachTest/VabQueryForm/components/VabQueryFormTopPanel.vue')['default']
  }
}

export { }
